🐞 BottomSheet crashes when rotating from landscape
[root-cause] When the device is in landscape with the BottomSheet opened
and the user rotates the device, it crashes with the following message:

 java.lang.IllegalArgumentException: The initial value must have an
 associated anchor.

 [solution] Although we don't have an official solution for this issue
 (see linked IssueTracker), I was able to find a workaround to avoid
 this bug.

 First of all, I used a `BoxWithConstraints` to know exactly when the
 device is in landscape mode. When in landscape, the
 `ModalBottomSheetLayout` has a weird behavior related to its height: it
 allows only `fillMaxHeight` or values lower the half screen. Since I
 don't want the BottomSheet to be fullscreen, I updated the code with
 using fractions of the screen. When the app is in portrait, it uses
 one value and when in landscape, other one.
 I also added a vertical scroll on the card. Not the best approach
 in UI point of view, but it will help users in landscape.